'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
/* Authentication States */

var AUTH_AUTHENTICATE = exports.AUTH_AUTHENTICATE = 'AUTH_CHECK_AUTHENTICATION';

var AUTH_SET_AUTHENTICATION = exports.AUTH_SET_AUTHENTICATION = 'AUTH_SET_AUTHENTICATION';

var AUTH_UNAUTHORIZED = exports.AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED';

var AUTH_AUTHORIZED = exports.AUTH_AUTHORIZED = 'AUTH_AUTHORIZED';

var AUTH_FAILED = exports.AUTH_FAILED = 'AUTH_FAILED';

var AUTH_USER_REQUESTED = exports.AUTH_USER_REQUESTED = 'AUTH_USER_REQUESTED';

var AUTH_USER_RETRIEVED = exports.AUTH_USER_RETRIEVED = 'AUTH_USER_RETRIEVED';

var AUTH_SET_USER = exports.AUTH_SET_USER = 'AUTH_SET_USER';

var AUTH_USER_FAILED = exports.AUTH_USER_FAILED = 'AUTH_USER_FAILED';

var AUTH_CLEAR_USER = exports.AUTH_CLEAR_USER = 'AUTH_CLEAR_USER';

var AUTH_CLEAR_AUTHENTICATION = exports.AUTH_CLEAR_AUTHENTICATION = 'AUTH_CLEAR_AUTHENTICATION';

var AUTH_AUTHENTICATED = exports.AUTH_AUTHENTICATED = 'AUTH_AUTHENTICATED';

var AUTH_UNAUTHENTICATED = exports.AUTH_UNAUTHENTICATED = 'AUTH_UNAUTHENTICATED';