/* Authentication States */

export const AUTH_AUTHENTICATE = 'AUTH_CHECK_AUTHENTICATION';

export const AUTH_SET_AUTHENTICATION = 'AUTH_SET_AUTHENTICATION';

export const AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED';

export const AUTH_AUTHORIZED = 'AUTH_AUTHORIZED';

export const AUTH_FAILED = 'AUTH_FAILED';

export const AUTH_USER_REQUESTED = 'AUTH_USER_REQUESTED';

export const AUTH_USER_RETRIEVED = 'AUTH_USER_RETRIEVED';

export const AUTH_SET_USER = 'AUTH_SET_USER';

export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';

export const AUTH_CLEAR_USER = 'AUTH_CLEAR_USER';

export const AUTH_CLEAR_AUTHENTICATION = 'AUTH_CLEAR_AUTHENTICATION';

export const AUTH_AUTHENTICATED = 'AUTH_AUTHENTICATED';

export const AUTH_UNAUTHENTICATED = 'AUTH_UNAUTHENTICATED';
